config/routes.rb
Sbs5::Application.routes.draw do

  root to: "Styles#index"

  get '/sessions/new' => 'Sessions#new', as: 'new_session'
  post '/sessions' => 'Sessions#create', as: 'sessions'
  delete '/sessions' => 'Sessions#destroy'

  resources :requirement_styles

  resources :requirements

  resources :styles

  resources :users

end

app/models/style.rb
class Style < ActiveRecord::Base
  attr_accessible :amenity, :exterior, :interior, :people, :image, :remote_image_url

  mount_uploader :image, ImageUploader

  has_many :requirements, :through => :requirement_styles
  belongs_to :requirement_styles
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  # GET /styles
  # GET /styles.json
  def index
    @styles = Style.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @styles }
    end
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
    @style = Style.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @style }
    end
  end

  # GET /styles/new
  # GET /styles/new.json
  def new
    @style = Style.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @style }
    end
  end

  # GET /styles/1/edit
  def edit
    @style = Style.find(params[:id])
  end

  # POST /styles
  # POST /styles.json
  def create
    @style = Style.new(params[:style])

    respond_to do |format|
      if @style.save
        format.html { redirect_to @style, notice: 'Style was successfully created.' }
        format.json { render json: @style, status: :created, location: @style }
      else
        format.html { render action: "new" }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /styles/1
  # PUT /styles/1.json
  def update
    @style = Style.find(params[:id])

    respond_to do |format|
      if @style.update_attributes(params[:style])
        format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.json
  def destroy
    @style = Style.find(params[:id])
    @style.destroy

    respond_to do |format|
      format.html { redirect_to styles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= form_for(@style) do |f| %>
  <% if @style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% @style.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.file_field :image %>
  </div>
  <div>
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </div>
  <div class="field">
    <%= f.label :exterior %><br />
    <%= f.check_box :exterior %>
  </div>
  <div class="field">
    <%= f.label :interior %><br />
    <%= f.check_box :interior %>
  </div>
  <div class="field">
    <%= f.label :people %><br />
    <%= f.check_box :people %>
  </div>
  <div class="field">
    <%= f.label :amenity %><br />
    <%= f.check_box :amenity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/styles/edit.html.erb
<h1>Editing style</h1>

<%= render 'form' %>

<%= link_to 'Show', @style %> |
<%= link_to 'Back', styles_path %>

app/views/styles/index.html.erb
<h1>Listing styles</h1>

<table>
  <tr>
    <th>Exterior</th>
    <th>Interior</th>
    <th>People</th>
    <th>Amenity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @styles.each do |style| %>
  <tr>
    <td><%= link_to image_tag style.image_url(:thumb).to_s %></td>
    <td><%= style.exterior %></td>
    <td><%= style.interior %></td>
    <td><%= style.people %></td>
    <td><%= style.amenity %></td>
    <td><%= link_to 'Show', style %></td>
    <td><%= link_to 'Edit', edit_style_path(style) %></td>
    <td><%= link_to 'Destroy', style, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Style', new_style_path %>

app/views/styles/new.html.erb
<h1>New style</h1>

<%= render 'form' %>

<%= link_to 'Back', styles_path %>

app/views/styles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Exterior:</b>
  <%= @style.exterior %>
</p>

<p>
  <b>Interior:</b>
  <%= @style.interior %>
</p>

<p>
  <b>People:</b>
  <%= @style.people %>
</p>

<p>
  <b>Amenity:</b>
  <%= @style.amenity %>
</p>


<%= link_to 'Edit', edit_style_path(@style) %> |
<%= link_to 'Back', styles_path %>