config/routes.rb
Sbs5::Application.routes.draw do

  root to: "Styles#index"

  get '/sessions/new' => 'Sessions#new', as: 'new_session'
  post '/sessions' => 'Sessions#create', as: 'sessions'
  delete '/sessions' => 'Sessions#destroy'

  resources :requirement_styles

  resources :requirements

  resources :styles

  resources :users

end

app/models/requirement_style.rb
class RequirementStyle < ActiveRecord::Base
  attr_accessible :requirement_id, :style_id
end

app/controllers/requirement_styles_controller.rb
class RequirementStylesController < ApplicationController
  # GET /requirement_styles
  # GET /requirement_styles.json
  def index
    @requirement_styles = RequirementStyle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requirement_styles }
    end
  end

  # GET /requirement_styles/1
  # GET /requirement_styles/1.json
  def show
    @requirement_style = RequirementStyle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @requirement_style }
    end
  end

  # GET /requirement_styles/new
  # GET /requirement_styles/new.json
  def new
    @requirement_style = RequirementStyle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @requirement_style }
    end
  end

  # GET /requirement_styles/1/edit
  def edit
    @requirement_style = RequirementStyle.find(params[:id])
  end

  # POST /requirement_styles
  # POST /requirement_styles.json
  def create
    @requirement_style = RequirementStyle.new(params[:requirement_style])

    respond_to do |format|
      if @requirement_style.save
        format.html { redirect_to @requirement_style, notice: 'Requirement style was successfully created.' }
        format.json { render json: @requirement_style, status: :created, location: @requirement_style }
      else
        format.html { render action: "new" }
        format.json { render json: @requirement_style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requirement_styles/1
  # PUT /requirement_styles/1.json
  def update
    @requirement_style = RequirementStyle.find(params[:id])

    respond_to do |format|
      if @requirement_style.update_attributes(params[:requirement_style])
        format.html { redirect_to @requirement_style, notice: 'Requirement style was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @requirement_style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requirement_styles/1
  # DELETE /requirement_styles/1.json
  def destroy
    @requirement_style = RequirementStyle.find(params[:id])
    @requirement_style.destroy

    respond_to do |format|
      format.html { redirect_to requirement_styles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/requirement_styles_helper.rb
module RequirementStylesHelper
end

app/views/requirement_styles/_form.html.erb
<%= form_for(@requirement_style) do |f| %>
  <% if @requirement_style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@requirement_style.errors.count, "error") %> prohibited this requirement_style from being saved:</h2>

      <ul>
      <% @requirement_style.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :style_id %><br />
    <%= f.number_field :style_id %>
  </div>
  <div class="field">
    <%= f.label :requirement_id %><br />
    <%= f.number_field :requirement_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requirement_styles/edit.html.erb
<h1>Editing requirement_style</h1>

<%= render 'form' %>

<%= link_to 'Show', @requirement_style %> |
<%= link_to 'Back', requirement_styles_path %>

app/views/requirement_styles/index.html.erb
<h1>Listing requirement_styles</h1>

<table>
  <tr>
    <th>Style</th>
    <th>Requirement</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @requirement_styles.each do |requirement_style| %>
  <tr>
    <td><%= requirement_style.style_id %></td>
    <td><%= requirement_style.requirement_id %></td>
    <td><%= link_to 'Show', requirement_style %></td>
    <td><%= link_to 'Edit', edit_requirement_style_path(requirement_style) %></td>
    <td><%= link_to 'Destroy', requirement_style, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Requirement style', new_requirement_style_path %>

app/views/requirement_styles/new.html.erb
<h1>New requirement_style</h1>

<%= render 'form' %>

<%= link_to 'Back', requirement_styles_path %>

app/views/requirement_styles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Style:</b>
  <%= @requirement_style.style_id %>
</p>

<p>
  <b>Requirement:</b>
  <%= @requirement_style.requirement_id %>
</p>


<%= link_to 'Edit', edit_requirement_style_path(@requirement_style) %> |
<%= link_to 'Back', requirement_styles_path %>