config/routes.rb
Sbs5::Application.routes.draw do

  root to: "Styles#index"

  get '/sessions/new' => 'Sessions#new', as: 'new_session'
  post '/sessions' => 'Sessions#create', as: 'sessions'
  delete '/sessions' => 'Sessions#destroy'

  resources :requirement_styles

  resources :requirements

  resources :styles

  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Sbs5</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Sbs5</a>
        <div class="nav-collapse">
          <ul class="nav">

            <li><%= link_to "Home", root_url %></li>
            <li><%= link_to "Users", "/users" %></li>
            <li><%= link_to "Styles", "/styles" %></li>
            <li><%= link_to "Requirements", "/requirements" %></li>
            <li><%= link_to "Requirement Styles", "/requirement_styles" %></li>
            <li><a href="#about">About</a></li>
            <% if signed_in? %>
              <li><%= link_to current_user.first_name.capitalize, current_user %></li>
              <li><%= link_to "Sign Out", sessions_url, method: 'delete' %></li>
            <% else %>
              <li><%= link_to "Sign In", new_session_url %></li>
              <li><%= link_to "Sign Up", new_user_url %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">

    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
    <% end %>

    <%= yield %>


    <hr>

    <footer>
      <p>&copy; Company 2012</p>
    </footer>

  </div>

</body>
</html>